name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
#          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4
      - name: Run Intrig in isolation
        run: |
          set -euo pipefail
          TMP="$(mktemp -d)"
          echo "Installing @intrig/core into: $TMP"
          npm i --prefix "$TMP" -D @intrig/core@latest
          echo "Installed files:"
          ls -la "$TMP/node_modules/@intrig/core" | sed -n '1,200p'
          echo "Bins:"
          ls -la "$TMP/node_modules/.bin" | sed -n '1,200p'

          # Run the bin by absolute path (avoids PATH issues)
          "$TMP/node_modules/.bin/intrig" --help
          "$TMP/node_modules/.bin/intrig" generate --ci

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - name: Nx affected (lint, test, build)
        run: npx nx affected -t lint test build --verbose
        env:
          NX_DAEMON: "false"

